# Generated by Django 3.0 on 2019-06-09 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(db_column='班级名', max_length=20, verbose_name='班级名')),
                ('gdate', models.DateTimeField(db_column='创建时间', verbose_name='创建时间')),
                ('gnum', models.IntegerField(db_column='班级人数', verbose_name='班级人数')),
                ('ggirlnum', models.IntegerField(db_column='女生人数', verbose_name='女生人数')),
                ('gboynum', models.IntegerField(db_column='男生人数', verbose_name='男生人数')),
                ('isDelete', models.BooleanField(db_column='是否删除', default=False)),
                ('lastTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(db_column='名字', max_length=20, verbose_name='名字')),
                ('tgender', models.BooleanField(db_column='性别', default=True, verbose_name='性别')),
                ('tid', models.CharField(db_column='职工号', max_length=20, verbose_name='职工号')),
                ('isDelete', models.BooleanField(db_column='是否删除', default=False)),
                ('teacher', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'teachers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(db_column='名字', max_length=20, verbose_name='名字')),
                ('sgender', models.BooleanField(db_column='性别', default=True, verbose_name='性别')),
                ('sid', models.CharField(db_column='学号', max_length=20, verbose_name='学号')),
                ('smajor', models.CharField(db_column='专业', default='', max_length=20, verbose_name='专业')),
                ('isDelete', models.BooleanField(db_column='是否删除', default=False)),
                ('sgrade', models.ManyToManyField(to='myApp.Grade', verbose_name='班级')),
                ('student', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='gteacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_grade', to='myApp.Teacher', verbose_name='老师'),
        ),
    ]
