# Generated by Django 3.0 on 2019-06-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu', models.CharField(db_column='请假学生', default='', max_length=90, verbose_name='请假学生')),
                ('body', models.TextField(db_column='内容', verbose_name='内容')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('is_agree', models.BooleanField(db_column='状态', default=False, verbose_name='状态')),
                ('grade', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='grade_comment', to='myApp.Grade', verbose_name='班级')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
