# Generated by Django 3.0 on 2019-06-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_agree',
            field=models.NullBooleanField(db_column='状态', default=None, verbose_name='状态'),
        ),
    ]
